### ISSUE TITLE
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty

### ISSUE THREAD

**Issue by Oppodelldog** [Oppodelldog/droxy#45]
I tired PHPStorm integration under windows using droxy, but when adding the php interpreter
droxy logs show up an error. Seems to be something with terminal detection under windows.

Here's the log:

`PS C:\Users\user\PhpstormProjects\droxy-phpstorm-integration\bin> tail -f .\droxy.log
time="2018-04-07T11:04:32+02:00" level=info msg="configuration load from: 'C:\\Users\\user\\PhpstormProjects\\droxy-phpstorm-integration\\bin/droxy.toml'"
time="2018-04-07T11:04:32+02:00" level=info
time="2018-04-07T11:04:32+02:00" level=info msg="environment variables:"
time="2018-04-07T11:04:32+02:00" level=info msg="=::=::\\"
time="2018-04-07T11:04:32+02:00" level=info msg="ALLUSERSPROFILE=C:\\ProgramData"
time="2018-04-07T11:04:32+02:00" level=info msg="APPDATA=C:\\Users\\user\\AppData\\Roaming"
time="2018-04-07T11:04:32+02:00" level=info msg="asl.log=Destination=file"
time="2018-04-07T11:04:32+02:00" level=info msg="CommonProgramFiles=C:\\Program Files\\Common Files"
time="2018-04-07T11:04:32+02:00" level=info msg="CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files"
time="2018-04-07T11:04:32+02:00" level=info msg="CommonProgramW6432=C:\\Program Files\\Common Files"
time="2018-04-07T11:04:32+02:00" level=info msg="COMPUTERNAME=user-PC"
time="2018-04-07T11:04:32+02:00" level=info msg="ComSpec=C:\\WINDOWS\\system32\\cmd.exe"
time="2018-04-07T11:04:32+02:00" level=info msg="DOCKER_TOOLBOX_INSTALL_PATH=C:\\Program Files\\Docker Toolbox"
time="2018-04-07T11:04:32+02:00" level=info msg="FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer"
time="2018-04-07T11:04:32+02:00" level=info msg="FPS_BROWSER_USER_PROFILE_STRING=Default"
time="2018-04-07T11:04:32+02:00" level=info msg="FP_NO_HOST_CHECK=NO"
time="2018-04-07T11:04:32+02:00" level=info msg="GOPATH=F:\\shared-projects\\go-workspace"
time="2018-04-07T11:04:32+02:00" level=info msg="GOROOT=C:\\Go\\"
time="2018-04-07T11:04:32+02:00" level=info msg="GTK_BASEPATH=C:\\Program Files (x86)\\GtkSharp\\2.12\\"
time="2018-04-07T11:04:32+02:00" level=info msg="HOMEDRIVE=C:"
time="2018-04-07T11:04:32+02:00" level=info msg="HOMEPATH=\\Users\\user"
time="2018-04-07T11:04:32+02:00" level=info msg="LOCALAPPDATA=C:\\Users\\user\\AppData\\Local"
time="2018-04-07T11:04:32+02:00" level=info msg="LOGONSERVER=\\\\user-PC"
time="2018-04-07T11:04:32+02:00" level=info msg="MAGICK_CONFIGURE_PATH=C:\\Program Files (x86)\\OpenShot Video Editor\\ImageMagick\\etc\\configuration"
time="2018-04-07T11:04:32+02:00" level=info msg="NUMBER_OF_PROCESSORS=4"
time="2018-04-07T11:04:32+02:00" level=info msg="OneDrive=C:\\Users\\user\\OneDrive"
time="2018-04-07T11:04:32+02:00" level=info msg="OS=Windows_NT"
time="2018-04-07T11:04:32+02:00" level=info msg="Path=C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\HashiCorp\\Vagrant\\bin;C:\\Program Files (x86)\\AMD\\ATI.ACE\\Core-Static;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;F:\\shared-projects\\go-workspace\\bin;C:\\Program Files (x86)\\GtkSharp\\2.12\\bin;c:\\Python27\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\Go\\bin;C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Program Files\\Docker Toolbox"
time="2018-04-07T11:04:32+02:00" level=info msg="PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
time="2018-04-07T11:04:32+02:00" level=info msg="PROCESSOR_ARCHITECTURE=AMD64"
time="2018-04-07T11:04:32+02:00" level=info msg="PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel"
time="2018-04-07T11:04:32+02:00" level=info msg="PROCESSOR_LEVEL=6"
time="2018-04-07T11:04:32+02:00" level=info msg="PROCESSOR_REVISION=3c03"
time="2018-04-07T11:04:32+02:00" level=info msg="ProgramData=C:\\ProgramData"
time="2018-04-07T11:04:32+02:00" level=info msg="ProgramFiles=C:\\Program Files"
time="2018-04-07T11:04:32+02:00" level=info msg="ProgramFiles(x86)=C:\\Program Files (x86)"
time="2018-04-07T11:04:32+02:00" level=info msg="ProgramW6432=C:\\Program Files"
time="2018-04-07T11:04:32+02:00" level=info msg="PSModulePath=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\"
time="2018-04-07T11:04:32+02:00" level=info msg="PUBLIC=C:\\Users\\Public"
time="2018-04-07T11:04:32+02:00" level=info msg="QT_PLUGIN_PATH=C:\\Program Files (x86)\\OpenShot Video Editor\\"
time="2018-04-07T11:04:32+02:00" level=info msg="SESSIONNAME=Console"
time="2018-04-07T11:04:32+02:00" level=info msg="SystemDrive=C:"
time="2018-04-07T11:04:32+02:00" level=info msg="SystemRoot=C:\\WINDOWS"
time="2018-04-07T11:04:32+02:00" level=info msg="TEMP=C:\\Users\\user\\AppData\\Local\\Temp"
time="2018-04-07T11:04:32+02:00" level=info msg="TMP=C:\\Users\\user\\AppData\\Local\\Temp"
time="2018-04-07T11:04:32+02:00" level=info msg="USERDOMAIN=user-PC"
time="2018-04-07T11:04:32+02:00" level=info msg="USERDOMAIN_ROAMINGPROFILE=user-PC"
time="2018-04-07T11:04:32+02:00" level=info msg="USERNAME=user"
time="2018-04-07T11:04:32+02:00" level=info msg="USERPROFILE=C:\\Users\\user"
time="2018-04-07T11:04:32+02:00" level=info msg="VBOX_MSI_INSTALL_PATH=C:\\Program Files\\Oracle\\VirtualBox\\"
time="2018-04-07T11:04:32+02:00" level=info msg="VS100COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\"
time="2018-04-07T11:04:32+02:00" level=info msg="VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\"
time="2018-04-07T11:04:32+02:00" level=info msg="windir=C:\\WINDOWS"
time="2018-04-07T11:04:32+02:00" level=info msg=----------------------------------------------------------------------
time="2018-04-07T11:04:32+02:00" level=info msg="origin arguments:"
time="2018-04-07T11:04:32+02:00" level=info msg="C:\\Users\\user\\PhpstormProjects\\droxy-phpstorm-integration\\bin\\php7.2.exe"
time="2018-04-07T11:04:32+02:00" level=info msg="C:\\Users\\user\\AppData\\Local\\Temp\\ide-phpinfo.php"
time="2018-04-07T11:04:32+02:00" level=info msg=----------------------------------------------------------------------
time="2018-04-07T11:04:32+02:00" level=info msg="calling docker ro tun 'php7.2'"
time="2018-04-07T11:04:32+02:00" level=info msg="docker run -t --rm --name php7.2 -v /C/Users/user/AppData/Local/Temp:/C/Users/user/AppData/Local/Temp -v /C/Users/user/PhpstormProjects/droxy-phpstorm-integration:/C/Users/user/PhpstormProjects/droxy-phpstorm-integration -e XDEBUG_CONFIG= -a STDIN -a STDOUT -a STDERR php:7.2 C:\\Users\\user\\AppData\\Local\\Temp\\ide-phpinfo.php"
time="2018-04-07T11:04:32+02:00" level=info msg="StdErr:the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'\n"
time="2018-04-07T11:04:32+02:00" level=info msg="docker finished with exit code '1'"`

**Comment by Oppodelldog** [comment]
solves the issue by setting config value **isTerminal=false**

**Comment by mateus-nogueira-matrix** [comment]
try to run on powershell terminal
